[project]
name = "llmbuster"
site_name = "llmbuster"
description = "A terminal-based (TUI) security scanner for assessing LLM implementations against the OWASP Top 10 for LLMs."
repo_url = "https://github.com/g-goessel/llmbuster"

[project.license]
type = "Apache License 2.0"
url = "https://www.apache.org/licenses/LICENSE-2.0"

[build]
output = "site"
