from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from llmbuster.cli import app
from llmbuster.domain.models import OwaspCategory, Verdict
from llmbuster.report import (
    ReportData,
    ReportError,
    build_report,
    render_json,
    render_markdown,
)
from llmbuster.store import InteractionRecord, RunRecord, SQLiteStore

runner = CliRunner()


def _make_run(
    target_kind: str = "profile",
    target_name: str | None = "Bot",
    model: str | None = "gpt-x",
    system_prompt: str | None = "you are a helpful bot",
) -> RunRecord:
    return RunRecord(
        started_at="2026-07-04T12:00:00+00:00",
        target_kind=target_kind,
        target_name=target_name,
        model=model,
        system_prompt=system_prompt,
        config_json='{"repeat":2}',
    )


def _make_interaction(
    run_id: int,
    *,
    payload_id: str = "llm01-direct-override",
    owasp: OwaspCategory = OwaspCategory.LLM01,
    attempt: int = 0,
    verdict: Verdict = Verdict.VULNERABLE,
    mutation: str | None = None,
    ttft_ms: int | None = 100,
    duration_ms: int | None = 300,
    tps: float | None = 42.5,
    response_text: str | None = "PWNED",
    detector_id: str | None = "canary",
    detector_detail: str | None = "token PWNED found",
) -> InteractionRecord:
    return InteractionRecord(
        run_id=run_id,
        payload_id=payload_id,
        owasp_category=owasp.value,
        attempt_index=attempt,
        mutation=mutation,
        escalation_from=None,
        sent_history_json='{"messages":[{"role":"user","content":"hi"}]}',
        raw_request_json='{"body":"hi"}',
        raw_response_text="raw-response",
        response_text=response_text,
        ttft_ms=ttft_ms,
        duration_ms=duration_ms,
        tps=tps,
        prompt_tokens=5,
        completion_tokens=9,
        verdict=verdict.value,
        detector_id=detector_id,
        detector_detail=detector_detail,
        created_at="2026-07-04T12:00:01+00:00",
    )


def _seed_db(db_path: Path) -> int:
    store = SQLiteStore(db_path)
    run_id = store.create_run(_make_run())
    store.insert_interaction(
        _make_interaction(
            run_id,
            payload_id="p1",
            owasp=OwaspCategory.LLM01,
            attempt=0,
            verdict=Verdict.VULNERABLE,
            ttft_ms=100,
            tps=10.0,
            response_text="PWNED secret leak",
        )
    )
    store.insert_interaction(
        _make_interaction(
            run_id,
            payload_id="p1",
            owasp=OwaspCategory.LLM01,
            attempt=1,
            verdict=Verdict.SAFE,
            ttft_ms=200,
            tps=20.0,
            response_text="I cannot help with that.",
        )
    )
    store.insert_interaction(
        _make_interaction(
            run_id,
            payload_id="p2",
            owasp=OwaspCategory.LLM02,
            attempt=0,
            verdict=Verdict.VULNERABLE,
            ttft_ms=None,
            tps=None,
            response_text="leaked data",
        )
    )
    store.insert_interaction(
        _make_interaction(
            run_id,
            payload_id="p3",
            owasp=OwaspCategory.LLM02,
            attempt=0,
            verdict=Verdict.ERROR,
            ttft_ms=None,
            tps=None,
            response_text=None,
        )
    )
    store.close()
    return run_id


def test_build_report_seeds(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    store = SQLiteStore(db)
    try:
        data = build_report(store, run_id)
    finally:
        store.close()

    assert isinstance(data, ReportData)
    assert data.run.id == run_id
    assert data.stats.total_interactions == 4
    assert data.stats.total_vulnerable == 2
    assert len(data.findings) == 2
    assert len(data.categories) == 2
    assert len(data.vulnerable_payloads) == 2
    assert len(data.all_interactions) == 4
    vuln_payload_ids = {p.payload_id for p in data.vulnerable_payloads}
    assert vuln_payload_ids == {"p1", "p2"}


def test_render_markdown_structure(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    store = SQLiteStore(db)
    try:
        data = build_report(store, run_id)
    finally:
        store.close()

    md = render_markdown(data)
    assert "# llmbuster Run Report" in md
    assert f"Run {run_id}" in md
    assert "## Executive Summary" in md
    assert "## Per-Category Summary" in md
    assert "## Reproducibly Vulnerable Payloads" in md
    assert "## Findings Detail" in md
    assert "### p1" in md
    assert "Generated by llmbuster" in md


def test_render_markdown_dashes_for_none(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    store = SQLiteStore(db)
    try:
        data = build_report(store, run_id)
    finally:
        store.close()

    md = render_markdown(data)
    lines = md.splitlines()
    cat_table_start = lines.index(
        "| Category | Total | Vulnerable | Safe | Error | Vuln Rate | "
        "Avg TTFT (ms) | Avg TPS | Avg Duration (ms) |"
    )
    llm02_row = next(
        line for line in lines[cat_table_start:] if line.startswith("| LLM02")
    )
    cols = [c.strip() for c in llm02_row.split("|")]
    assert "LLM02" in cols
    assert "-" in cols
    assert "50.0%" in llm02_row


def test_render_json_is_valid_json(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    store = SQLiteStore(db)
    try:
        data = build_report(store, run_id)
    finally:
        store.close()

    payload = render_json(data)
    obj = json.loads(payload)
    for key in (
        "run",
        "stats",
        "categories",
        "vulnerable_payloads",
        "findings",
        "all_interactions",
    ):
        assert key in obj, f"missing key: {key}"
    assert isinstance(obj["findings"], list)
    assert len(obj["findings"]) == 2
    finding = obj["findings"][0]
    for field in (
        "payload_id",
        "owasp_category",
        "verdict",
        "response_text",
        "ttft_ms",
        "duration_ms",
        "tps",
        "detector_id",
    ):
        assert field in finding, f"missing finding field: {field}"


def test_build_report_missing_run_raises(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    assert run_id >= 1
    store = SQLiteStore(db)
    try:
        with pytest.raises(ReportError):
            build_report(store, 99999)
    finally:
        store.close()


def test_cli_report_markdown_to_file(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    out = tmp_path / "report.md"
    result = runner.invoke(
        app,
        [
            "report",
            str(run_id),
            "--db",
            str(db),
            "--format",
            "markdown",
            "--out",
            str(out),
        ],
    )
    assert result.exit_code == 0, result.output
    assert out.exists()
    content = out.read_text(encoding="utf-8")
    assert "## Executive Summary" in content
    assert f"Run {run_id}" in content
    assert f"Wrote report to {out}" in result.output


def test_cli_report_json_to_stdout(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    result = runner.invoke(
        app,
        ["report", str(run_id), "--db", str(db), "--format", "json"],
    )
    assert result.exit_code == 0, result.output
    obj = json.loads(result.output)
    assert "run" in obj
    assert "stats" in obj
    assert obj["run"]["id"] == run_id


def test_cli_report_missing_run_exits_1(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    _seed_db(db)
    result = runner.invoke(app, ["report", "99999", "--db", str(db)])
    assert result.exit_code == 1
    assert "not found" in result.output


def test_cli_report_invalid_format_exits_1(tmp_path: Path) -> None:
    db = tmp_path / "t.db"
    run_id = _seed_db(db)
    result = runner.invoke(
        app,
        ["report", str(run_id), "--db", str(db), "--format", "xml"],
    )
    assert result.exit_code == 1
    assert "xml" in result.output
